### ISSUE TITLE
xrandr: Configure crtc 0 failed

### ISSUE THREAD

**Issue by ma1ko** [phillipberndt/autorandr#35] opened 2015-05-29 21:49 UTC
$ cat /var/log/autorandr.log 
    xrandr: Configure crtc 0 failed
    xrandr: Configure crtc 0 failed
    default (detected)
    extern (detected) (current)
    laptop (detected)
    Failed to apply profile 'default' (line 591):
      Command failed: xrandr --query --output VGA1 --off (line 591)
    This appears to be a bug. Please help improving autorandr by reporting it upstream.
    Please attach the output of `xrandr --verbose` to your bug report if appropriate.

This happens when I disconnect my laptop from the docking station. Both external monitors (VGA1 and HDMI3) fail to turn off and the laptop screen (LVDS1) does not turn on. From there, i can either switch to a virtual console and restart X or put the laptop back in the docking station.

xrandr log while only laptop screen is attached (done from a virtual console): http://pastebin.com/NVAJc2Xj

**Comment by phillipberndt** [comment] 2015-05-30 08:48
The issue might be that xrandr does not recognizes the external monitors as disconnected.

Is the log from before or after the script tried to run autorandr? If it's from after, please disable the udev script for now (or recreate the log from the sleep.d-script) and attach what `xrandr --verbose` outputs then. `autorandr -c --dry-run`'s output might be helpful, too.

**Comment by ma1ko** [comment] 2015-05-30 14:39
I am no longer able to reproduce this issue. I installed wertarbyte/autorandr, with which everything worked. Than I again installed your version of autorandr, which then also worked.

The posted log file was after running autorandr. However, the output is the same before and after running autorandr, since it aborted with an error and did not change anything.

Autorandr should not have detected the 'extern' configuration, since it used both external monitors which were not connected anymore.

**Comment by phillipberndt** [comment] 2015-05-30 14:42
> The posted log file was after running autorandr. However, the output is the same before and after
> running autorandr, since it aborted with an error and did not change anything.

xrandr does not revert to the old settings if a part of the command fails. A non-zero exit state does not imply that nothing changed.

> Autorandr should not have detected the 'extern' configuration, since it used both external monitors 
> which were not connected anymore.

Do you still have the `setup` file for the extern configuration?

**Comment by ma1ko** [comment] 2015-05-30 14:59
>Do you still have the setup file for the extern configuration?

        $cat extern/config
        output DP1
        off
        output DP2
        off
        output DP3
        off
        output HDMI1
        off
        output HDMI2
        off
        output VIRTUAL1
        off
        output LVDS1
        off
        output VGA1
        mode 1920x1080
        pos 0x0
        rate 60.00
        output HDMI3
        mode 1680x1050
        pos 1920x0
        rate 59.88

        $cat extern/setup
        HDMI3 00ffffffffffff001e6d78567202010007120103ea312078eaaec5a2574a9c25125054a76b80950081808140714f01010101010101017c2e90a0601a1e4030203600da281100001a21399030621a274068b03600da281100001c000000fd00384b1e530f000a202020202020000000fc0057323234320a2020202020202000f0
        LVDS1 00ffffffffffff0030aeb240000000000113010380221378ea2135ad5037aa24115054000000010101010101010101010101010101014c368082703832403c30aa0058c1100000183f2d8082703832403c30aa0058c1100000180000000f00d10932d109281b190006af5634000000fe004231353648573031205634200a00d6
        VGA1 00ffffffffffff0034a44536010101012714010368341e782aeed5a555489b26125054bfef80b300a940950081408180950f714f9040023a801871382d40582c450009252100001e000000ff005630333954533630353034350a000000fd00374c1d5111000a202020202020000000fc004d442032303331300a202020200057


the default configuration has VGA1 und HDMI3 turned off and only LVDS1 (the laptop monitor) turned on

**Comment by phillipberndt** [comment] 2015-05-30 17:15
Thanks! I can't reproduce this either. Apparently this was fixed with 36372f5 (HEAD~49), that was the newest version for which I could reproduce this issue.

**Closed by phillipberndt** 2015-05-30 17:15 UTC
